package com.eyarko.ecom.controller;

import com.eyarko.ecom.dto.ApiResponse;
import com.eyarko.ecom.util.ResponseUtil;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * Demonstration controller for CSRF protection with form submissions.
 * <p>
 * This controller demonstrates CSRF token mechanism for form-based endpoints.
 * CSRF protection is enabled for form endpoints to protect against cross-site request forgery attacks.
 * <p>
 * <b>When to use CSRF protection:</b>
 * <ul>
 *   <li>Stateful session-based authentication (cookies)</li>
 *   <li>HTML form submissions (application/x-www-form-urlencoded)</li>
 *   <li>Browser-based applications using session cookies</li>
 * </ul>
 * <p>
 * <b>When CSRF is NOT needed:</b>
 * <ul>
 *   <li>Stateless JWT-based APIs (tokens in Authorization headers)</li>
 *   <li>REST APIs using JSON payloads</li>
 *   <li>APIs that don't use cookies for authentication</li>
 * </ul>
 */
@RestController
@RequestMapping("/api/v1/demo")
public class FormDemoController {

    /**
     * Endpoint to retrieve CSRF token for form submissions.
     * <p>
     * This endpoint returns the CSRF token that must be included in form submissions.
     * The token is automatically generated by Spring Security when CSRF protection is enabled.
     *
     * @param request HTTP request (contains CSRF token)
     * @return CSRF token
     */
    @GetMapping("/csrf-token")
    public ApiResponse<String> getCsrfToken(HttpServletRequest request) {
        CsrfToken csrfToken = (CsrfToken) request.getAttribute("_csrf");
        if (csrfToken != null) {
            return ResponseUtil.success("CSRF token retrieved", csrfToken.getToken());
        }
        return ResponseUtil.success("CSRF protection not enabled for this endpoint", null);
    }

    /**
     * Form submission endpoint with CSRF protection enabled.
     * <p>
     * This endpoint demonstrates CSRF protection for form submissions.
     * The CSRF token must be included in the request (either as a header or form parameter).
     * <p>
     * <b>Testing with Postman:</b>
     * <ol>
     *   <li>First, GET /api/v1/demo/csrf-token to retrieve the CSRF token</li>
     *   <li>Include the token in your POST request:
     *     <ul>
     *       <li>As header: X-CSRF-TOKEN: &lt;token&gt;</li>
     *       <li>Or as form parameter: _csrf: &lt;token&gt;</li>
     *     </ul>
     *   </li>
     *   <li>Without the token, the request will be rejected with 403 Forbidden</li>
     * </ol>
     * <p>
     * <b>Testing with browser:</b>
     * <ol>
     *   <li>Spring Security automatically includes CSRF token in forms</li>
     *   <li>Browser automatically sends the token with form submissions</li>
     *   <li>Same-origin policy protects against CSRF attacks</li>
     * </ol>
     *
     * @param message form data
     * @param request HTTP request (validates CSRF token)
     * @return success response
     */
    @PostMapping("/form-submit")
    public ApiResponse<String> submitForm(
        @RequestParam(required = false) String message,
        HttpServletRequest request
    ) {
        // CSRF token is automatically validated by Spring Security
        // If validation fails, request won't reach this method
        return ResponseUtil.success(
            "Form submitted successfully with CSRF protection",
            "Message received: " + (message != null ? message : "No message provided")
        );
    }
}

